import React from 'react';

function parseDailyBrief(content) {
  if (!content) return null;
  const lines = content.split('\n');
  
  const result = {
    date: '',
    generatedAt: '',
    schedule: [],
    completedToday: [],
    stillDueToday: [],
    overdueTasks: [],
    habits: {
      summary: '',
      doneCount: 0,
      totalCount: 0,
      list: []
    },
    comingUp: [],
    yesterday: {
      date: '',
      completed: [],
      fitness: [],
      health: null,
      rawLines: []
    },
    workout: {
      routine: '',
      exercises: []
    },
    rawSections: {
      schedule: [],
      completedToday: [],
      stillDueToday: [],
      overdueTasks: [],
      habits: [],
      comingUp: [],
      yesterday: [],
      workout: []
    }
  };

  let currentSection = '';
  let yesterdaySubSection = '';

  lines.forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed) return;

    if (trimmed.startsWith('# ')) {
      const dateMatch = trimmed.match(/Daily Brief\s*—\s*([\d-]+)/i);
      if (dateMatch) {
        result.date = dateMatch[1];
      } else {
        result.date = trimmed.substring(2);
      }
      return;
    }

    if (trimmed.startsWith('> Generated by')) {
      const timeMatch = trimmed.match(/at\s*([\d:]+)/i);
      if (timeMatch) {
        result.generatedAt = timeMatch[1];
      } else {
        result.generatedAt = trimmed.replace('>', '').trim();
      }
      return;
    }

    if (trimmed.startsWith('## ')) {
      const headerText = trimmed.substring(3).toLowerCase();
      if (headerText.includes('schedule')) {
        currentSection = 'schedule';
      } else if (headerText.includes('completed today')) {
        currentSection = 'completedToday';
      } else if (headerText.includes('still due today') || headerText.includes('still due')) {
        currentSection = 'stillDueToday';
      } else if (headerText.includes('overdue')) {
        currentSection = 'overdueTasks';
      } else if (headerText.includes('habit')) {
        currentSection = 'habits';
      } else if (headerText.includes('coming up')) {
        currentSection = 'comingUp';
      } else if (headerText.includes('yesterday')) {
        currentSection = 'yesterday';
        const dateMatch = trimmed.match(/\(([^)]+)\)/);
        if (dateMatch) {
          result.yesterday.date = dateMatch[1];
        }
      } else if (headerText.includes('workout') || headerText.includes('routine')) {
        currentSection = 'workout';
      } else {
        currentSection = '';
      }
      return;
    }

    if (currentSection && result.rawSections[currentSection]) {
      result.rawSections[currentSection].push(line);
    }

    if (currentSection === 'schedule') {
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\*\*([^\*]+)\*\*\s*\(([^)]+)\):\s*(.*?)(?:\s*—\s*\*?(.*?)\*?)?$/);
        if (match) {
          result.schedule.push({
            time: match[1],
            source: match[2],
            title: match[3],
            description: match[4] ? match[4].replace(/^\*|\*$/g, '') : ''
          });
        }
      }
    } else if (currentSection === 'completedToday') {
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[x\]\s*(.*?)\s*\((.*?)\)(?:\s*at\s*([\d:]+))?$/i);
        if (match) {
          result.completedToday.push({
            title: match[1],
            category: match[2],
            time: match[3] || ''
          });
        }
      }
    } else if (currentSection === 'stillDueToday') {
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[\s*\]\s*(.*?)\s*\((.*?)\)$/i);
        if (match) {
          result.stillDueToday.push({
            title: match[1],
            category: match[2]
          });
        }
      }
    } else if (currentSection === 'overdueTasks') {
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[\s*\]\s*(.*?)\s*\((.*?)\)(?:\s*—\s*was due\s*([\d-]+)\s*\((.*?)\))?$/i);
        if (match) {
          result.overdueTasks.push({
            title: match[1],
            category: match[2],
            dueDate: match[3] || '',
            daysOverdue: match[4] || ''
          });
        }
      }
    } else if (currentSection === 'habits') {
      if (trimmed.startsWith('**')) {
        result.habits.summary = trimmed;
        const countMatch = trimmed.match(/\*\*(\d+)\/(\d+)\*\*/);
        if (countMatch) {
          result.habits.doneCount = parseInt(countMatch[1], 10);
          result.habits.totalCount = parseInt(countMatch[2], 10);
        }
      } else if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[(x| )\]\s*(.*?)(?:\s*\*\(not logged\)\*)?$/i);
        if (match) {
          result.habits.list.push({
            name: match[2].trim(),
            completed: match[1].toLowerCase() === 'x',
            notLogged: item.includes('not logged')
          });
        }
      }
    } else if (currentSection === 'comingUp') {
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[\s*\]\s*(.*?)\s*\((.*?)\)(?:\s*📅\s*([\d-]+))?$/i);
        if (match) {
          result.comingUp.push({
            title: match[1],
            category: match[2],
            dueDate: match[3] || ''
          });
        }
      }
    } else if (currentSection === 'yesterday') {
      result.yesterday.rawLines.push(line);
      if (trimmed.startsWith('### ')) {
        const subHeader = trimmed.substring(4).toLowerCase();
        if (subHeader.includes('completed')) {
          yesterdaySubSection = 'completed';
        } else if (subHeader.includes('fitness')) {
          yesterdaySubSection = 'fitness';
        } else if (subHeader.includes('health')) {
          yesterdaySubSection = 'health';
        } else {
          yesterdaySubSection = '';
        }
      } else if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        if (yesterdaySubSection === 'completed') {
          const match = item.match(/^\[x\]\s*(.*?)\s*\((.*?)\)$/i);
          if (match) {
            result.yesterday.completed.push({
              title: match[1],
              category: match[2]
            });
          }
        } else if (yesterdaySubSection === 'fitness') {
          result.yesterday.fitness.push(item);
        } else if (yesterdaySubSection === 'health') {
          result.yesterday.health = item;
        }
      }
    } else if (currentSection === 'workout') {
      if (trimmed.startsWith('**Routine**:') || trimmed.startsWith('**Routine**')) {
        result.workout.routine = trimmed.replace(/^\*\*Routine\*\*:\s*|^\*\*Routine\s*:\s*/, '').trim();
      } else if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        const match = item.match(/^\[(x| )\]\s*(.*?)$/i);
        if (match) {
          result.workout.exercises.push({
            name: match[2].trim(),
            completed: match[1].toLowerCase() === 'x'
          });
        } else {
          result.workout.exercises.push({
            name: item.trim(),
            completed: false
          });
        }
      }
    }
  });

  return result;
}

function LinearMarkdownRenderer({ content }) {
  if (!content) return null;
  const lines = content.split('\n');
  let inList = false;
  let listItems = [];
  const renderedElements = [];
  
  const flushList = (key) => {
    if (listItems.length > 0) {
      renderedElements.push(
        <ul key={`list-${key}`} className="brief-list" style={{ paddingLeft: '0rem', marginBottom: '1rem', listStyle: 'none' }}>
          {listItems}
        </ul>
      );
      listItems = [];
      inList = false;
    }
  };
  
  lines.forEach((line, idx) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('# ')) {
      flushList(idx);
      renderedElements.push(
        <h2 key={idx} className="brief-h1" style={{ borderBottom: '1px dashed var(--accent-cyan)', paddingBottom: '0.5rem', marginBottom: '1rem', marginTop: '1.5rem', color: 'var(--accent-cyan)', fontFamily: 'var(--font-display)' }}>
          {trimmed.substring(2)}
        </h2>
      );
    } else if (trimmed.startsWith('## ')) {
      flushList(idx);
      renderedElements.push(
        <h3 key={idx} className="brief-h2" style={{ color: 'var(--accent-green)', marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.1rem', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '0.25rem', fontFamily: 'var(--font-display)' }}>
          {trimmed.substring(3)}
        </h3>
      );
    } else if (trimmed.startsWith('### ')) {
      flushList(idx);
      renderedElements.push(
        <h4 key={idx} className="brief-h3" style={{ color: 'var(--text-primary)', marginTop: '1rem', marginBottom: '0.5rem', fontSize: '0.95rem' }}>
          {trimmed.substring(4)}
        </h4>
      );
    } else if (trimmed.startsWith('> ')) {
      flushList(idx);
      renderedElements.push(
        <blockquote key={idx} className="brief-blockquote" style={{ borderLeft: '3px solid var(--accent-purple)', paddingLeft: '1rem', color: 'var(--text-muted)', fontStyle: 'italic', margin: '1rem 0' }}>
          {trimmed.substring(2)}
        </blockquote>
      );
    } else if (trimmed.startsWith('- ')) {
      inList = true;
      const listContent = trimmed.substring(2);
      if (listContent.startsWith('[ ]') || listContent.startsWith('[x]') || listContent.startsWith('[X]')) {
        const checked = listContent.startsWith('[x]') || listContent.startsWith('[X]');
        const text = listContent.substring(3).trim();
        listItems.push(
          <li key={idx} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.4rem', fontSize: '0.85rem' }}>
            <span className="material-symbols-outlined" style={{ fontSize: '1.1rem', color: checked ? 'var(--accent-pink)' : 'var(--text-muted)', userSelect: 'none' }}>
              {checked ? 'check_box' : 'check_box_outline_blank'}
            </span>
            <span style={{ textDecoration: checked ? 'line-through' : 'none', color: checked ? 'var(--text-muted)' : 'var(--text-primary)' }}>
              {text}
            </span>
          </li>
        );
      } else {
        listItems.push(
          <li key={idx} style={{ marginBottom: '0.4rem', fontSize: '0.85rem', color: 'var(--text-primary)', position: 'relative', paddingLeft: '1rem' }}>
            <span style={{ position: 'absolute', left: 0, color: 'var(--accent-cyan)' }}>•</span>
            {listContent}
          </li>
        );
      }
    } else if (trimmed === '') {
      flushList(idx);
    } else {
      flushList(idx);
      const parts = trimmed.split('**');
      const children = parts.map((part, pIdx) => {
        if (pIdx % 2 === 1) {
          return <strong key={pIdx} style={{ color: 'var(--text-primary)', fontWeight: 'bold' }}>{part}</strong>;
        }
        return part;
      });
      renderedElements.push(
        <p key={idx} className="brief-p" style={{ marginBottom: '0.75rem', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
          {children}
        </p>
      );
    }
  });
  
  flushList(lines.length);
  return <div className="brief-rendered-content">{renderedElements}</div>;
}

function RenderBrief({ content }) {
  if (!content) return <p style={{ color: 'var(--text-muted)' }}>No content.</p>;

  const parsed = parseDailyBrief(content);
  if (!parsed) return <LinearMarkdownRenderer content={content} />;

  const totalEvents = parsed.schedule.length;
  const habitsDone = parsed.habits.doneCount;
  const habitsTotal = parsed.habits.totalCount;
  const habitPercentage = habitsTotal > 0 ? Math.round((habitsDone / habitsTotal) * 100) : 0;
  const stillDueCount = parsed.stillDueToday.length;
  const overdueCount = parsed.overdueTasks.length;
  const completedCount = parsed.completedToday.length;
  const comingUpCount = parsed.comingUp.length;

  return (
    <div className="brief-dashboard-container flicker-effect">
      {/* Dashboard Header Banner */}
      <div className="brief-dashboard-header">
        <div className="brief-dashboard-header-inner">
          <div className="brief-header-meta">
            <h2 className="brief-header-title">[ ATHENA_DAILY_LOG: {parsed.date || 'LOG_SHEET'} ]</h2>
            <span className="brief-header-timestamp">
              <span className="material-symbols-outlined" style={{ fontSize: '0.8rem', verticalAlign: 'middle', marginRight: '0.25rem' }}>schedule</span>
              TELEMETRY GENERATED AT: {parsed.generatedAt || '00:00:00'}
            </span>
          </div>
          <div className="brief-header-stats">
            <div className="brief-stat-badge cyan">
              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem' }}>calendar_today</span>
              <span>{totalEvents} Events</span>
            </div>
            <div className="brief-stat-badge green">
              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem' }}>task_alt</span>
              <span>{completedCount} Done</span>
            </div>
            <div className="brief-stat-badge pink">
              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem' }}>warning</span>
              <span>{overdueCount} Overdue</span>
            </div>
            <div className="brief-stat-badge purple">
              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem' }}>sync</span>
              <span>{habitsDone}/{habitsTotal} Habits</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Responsive Grid */}
      <div className="brief-dashboard-grid">
        {/* Left Column: Timeline Schedule & Yesterday's Review */}
        <div className="brief-grid-col">
          {/* Card 1: Today's Schedule Timeline */}
          <div className="brief-card">
            <div className="brief-card-header">
              <h4 className="brief-card-title cyan">
                <span className="material-symbols-outlined">schedule</span>
                Today's Schedule
              </h4>
              <span className="brief-task-cat-badge">{totalEvents} Events</span>
            </div>
            <div className="brief-card-content">
              {totalEvents === 0 ? (
                <div className="brief-empty-notice">
                  <span className="material-symbols-outlined" style={{ fontSize: '1rem', color: 'var(--text-muted)' }}>calendar_today</span>
                  <span>No events scheduled for today. Vault is clear.</span>
                </div>
              ) : (
                <div className="brief-timeline">
                  {parsed.schedule.map((ev, idx) => (
                    <div key={idx} className="brief-timeline-node">
                      <div className="brief-timeline-dot"></div>
                      <div className="brief-timeline-header">
                        <span className="brief-timeline-time">{ev.time}</span>
                        <span className="brief-timeline-source">({ev.source})</span>
                      </div>
                      <div className="brief-timeline-title">{ev.title}</div>
                      {ev.description && <div className="brief-timeline-desc">{ev.description}</div>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Card 2: Yesterday's Review */}
          <div className="brief-card">
            <div className="brief-card-header">
              <h4 className="brief-card-title purple">
                <span className="material-symbols-outlined">history</span>
                Yesterday's Review {parsed.yesterday.date && `(${parsed.yesterday.date})`}
              </h4>
            </div>
            <div className="brief-card-content">
              {parsed.yesterday.completed.length === 0 && 
               parsed.yesterday.fitness.length === 0 && 
               !parsed.yesterday.health ? (
                <div className="brief-empty-notice">
                  <span className="material-symbols-outlined" style={{ fontSize: '1rem', color: 'var(--text-muted)' }}>history</span>
                  <span>No tracked activity recorded yesterday.</span>
                </div>
              ) : (
                <div className="brief-yesterday-row">
                  {parsed.yesterday.completed.length > 0 && (
                    <div className="brief-yesterday-section">
                      <div className="brief-yesterday-title">Completed Tasks</div>
                      <ul className="brief-yesterday-list">
                        {parsed.yesterday.completed.map((t, idx) => (
                          <li key={idx} className="brief-yesterday-list-item">
                            <span className="material-symbols-outlined" style={{ fontSize: '0.95rem', color: 'var(--accent-green)' }}>check</span>
                            <span>{t.title}</span>
                            <span className="brief-task-cat-badge">{t.category}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {parsed.yesterday.fitness.length > 0 && (
                    <div className="brief-yesterday-section">
                      <div className="brief-yesterday-title">Fitness Log</div>
                      <ul className="brief-yesterday-list">
                        {parsed.yesterday.fitness.map((fit, idx) => (
                          <li key={idx} className="brief-yesterday-list-item">
                            <span className="material-symbols-outlined" style={{ fontSize: '0.95rem', color: 'var(--accent-pink)' }}>directions_run</span>
                            <span>{fit}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {parsed.yesterday.health && (
                    <div className="brief-yesterday-section">
                      <div className="brief-yesterday-title">Biometrics & Vitals</div>
                      <div className="brief-yesterday-text" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <span className="material-symbols-outlined" style={{ fontSize: '1rem', color: 'var(--accent-cyan)' }}>monitor_heart</span>
                        <span>{parsed.yesterday.health}</span>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right Column: Habits & Task Status Board */}
        <div className="brief-grid-col">
          {/* Card 3: Habits Tracker */}
          <div className="brief-card">
            <div className="brief-card-header">
              <h4 className="brief-card-title green">
                <span className="material-symbols-outlined">sync</span>
                Habit Checklist
              </h4>
              <span className="brief-task-cat-badge">{habitsDone}/{habitsTotal} completed</span>
            </div>
            <div className="brief-card-content">
              {habitsTotal > 0 && (
                <div className="brief-habit-progress">
                  <div className="brief-habit-progress-header">
                    <span>Progress Matrix</span>
                    <span style={{ fontWeight: 'bold', color: 'var(--accent-green)' }}>{habitPercentage}%</span>
                  </div>
                  <div className="brief-progress-bar-bg">
                    <div className="brief-progress-bar-fill" style={{ width: `${habitPercentage}%` }}></div>
                  </div>
                </div>
              )}

              {parsed.habits.list.length === 0 ? (
                <div className="brief-empty-notice">
                  <span className="material-symbols-outlined" style={{ fontSize: '1rem' }}>sync_disabled</span>
                  <span>No habits queued for tracking today.</span>
                </div>
              ) : (
                <div className="brief-habit-list">
                  {parsed.habits.list.map((habit, idx) => (
                    <div key={idx} className={`brief-habit-item ${habit.completed ? 'completed' : ''} ${habit.notLogged ? 'not-logged' : ''}`}>
                      <span className="material-symbols-outlined habit-icon" style={{ fontSize: '1rem', userSelect: 'none' }}>
                        {habit.completed ? 'check_box' : habit.notLogged ? 'radio_button_unchecked' : 'check_box_outline_blank'}
                      </span>
                      <span style={{ textDecoration: habit.completed ? 'line-through' : 'none' }}>
                        {habit.name}
                      </span>
                      {habit.notLogged && <span style={{ fontSize: '0.65rem', marginLeft: 'auto', opacity: 0.6 }}>(not logged)</span>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Card 3.5: Today's Workout Routine */}
          {parsed.workout && parsed.workout.routine && (
            <div className="brief-card">
              <div className="brief-card-header">
                <h4 className="brief-card-title green" style={{ color: 'var(--accent-green)' }}>
                  <span className="material-symbols-outlined">directions_run</span>
                  Today's Workout
                </h4>
                <span className="brief-task-cat-badge">{parsed.workout.routine}</span>
              </div>
              <div className="brief-card-content">
                <div className="brief-habit-list">
                  {parsed.workout.exercises.map((ex, idx) => (
                    <div key={idx} className={`brief-habit-item ${ex.completed ? 'completed' : ''}`}>
                      <span className="material-symbols-outlined habit-icon" style={{ fontSize: '1rem', color: ex.completed ? 'var(--accent-green)' : 'var(--text-muted)' }}>
                        {ex.completed ? 'check_box' : 'check_box_outline_blank'}
                      </span>
                      <span style={{ textDecoration: ex.completed ? 'line-through' : 'none' }}>
                        {ex.name}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Card 4: Task Status Board */}
          <div className="brief-card">
            <div className="brief-card-header">
              <h4 className="brief-card-title pink">
                <span className="material-symbols-outlined">assignment</span>
                Task Status Board
              </h4>
            </div>
            <div className="brief-card-content">
              {stillDueCount === 0 && overdueCount === 0 && completedCount === 0 && comingUpCount === 0 ? (
                <div className="brief-empty-notice">
                  <span className="material-symbols-outlined" style={{ fontSize: '1rem' }}>assignment_turned_in</span>
                  <span>No tasks listed in the briefing sheets.</span>
                </div>
              ) : (
                <div className="brief-task-board">
                  {/* Sub-Section 1: Overdue Tasks */}
                  {overdueCount > 0 && (
                    <div className="brief-task-section">
                      <div className="brief-task-section-title pink">Overdue / Pushed Off ({overdueCount})</div>
                      <div className="brief-task-list">
                        {parsed.overdueTasks.map((t, idx) => (
                          <div key={idx} className="brief-task-card">
                            <div className="brief-task-info">
                              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem', color: 'var(--accent-pink)' }}>warning</span>
                              <span className="brief-task-title">{t.title}</span>
                              <span className="brief-task-cat-badge">{t.category}</span>
                            </div>
                            {t.daysOverdue && (
                              <span className="brief-task-due-badge overdue">{t.daysOverdue}</span>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Sub-Section 2: Outstanding Tasks */}
                  {stillDueCount > 0 && (
                    <div className="brief-task-section">
                      <div className="brief-task-section-title cyan">Still Due Today ({stillDueCount})</div>
                      <div className="brief-task-list">
                        {parsed.stillDueToday.map((t, idx) => (
                          <div key={idx} className="brief-task-card">
                            <div className="brief-task-info">
                              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem', color: 'var(--accent-cyan)' }}>radio_button_unchecked</span>
                              <span className="brief-task-title">{t.title}</span>
                              <span className="brief-task-cat-badge">{t.category}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Sub-Section 3: Completed Today */}
                  {completedCount > 0 && (
                    <div className="brief-task-section">
                      <div className="brief-task-section-title green">Completed Today ({completedCount})</div>
                      <div className="brief-task-list">
                        {parsed.completedToday.map((t, idx) => (
                          <div key={idx} className="brief-task-card completed">
                            <div className="brief-task-info">
                              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem', color: 'var(--accent-green)' }}>check_circle</span>
                              <span className="brief-task-title">{t.title}</span>
                              <span className="brief-task-cat-badge">{t.category}</span>
                            </div>
                            {t.time && <span className="brief-task-status-time">{t.time}</span>}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Sub-Section 4: Coming Up Next */}
                  {comingUpCount > 0 && (
                    <div className="brief-task-section">
                      <div className="brief-task-section-title purple">Coming Up Next ({comingUpCount})</div>
                      <div className="brief-task-list">
                        {parsed.comingUp.map((t, idx) => (
                          <div key={idx} className="brief-task-card">
                            <div className="brief-task-info">
                              <span className="material-symbols-outlined" style={{ fontSize: '0.9rem', color: 'var(--accent-purple)' }}>calendar_today</span>
                              <span className="brief-task-title">{t.title}</span>
                              <span className="brief-task-cat-badge">{t.category}</span>
                            </div>
                            {t.dueDate && (
                              <span className="brief-task-due-badge future">{t.dueDate}</span>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Raw Markdown Fallback Dropdown */}
      <details className="brief-fallback-details">
        <summary className="brief-fallback-summary">
          <span className="material-symbols-outlined" style={{ fontSize: '0.9rem', verticalAlign: 'middle', marginRight: '0.35rem' }}>terminal</span>
          DIAGNOSTIC DATA: VIEW RAW BRIEF LOG
        </summary>
        <div className="brief-fallback-content">
          <LinearMarkdownRenderer content={content} />
        </div>
      </details>
    </div>
  );
}

function BriefPanel({ selectedBrief, generatingBrief, handleGenerateBrief }) {
  return (
    <div>
      <header className="page-header" style={{ marginBottom: '1.5rem' }}>
        <div className="page-header-inner">
          <div>
            <h1 className="page-title text-gradient-cyan glitch-text">Daily Brief</h1>
            <p className="page-subtitle">Intelligence Log: Diurnal Recaps</p>
          </div>
          <button 
            className="btn-primary" 
            onClick={handleGenerateBrief} 
            disabled={generatingBrief}
            style={{ fontSize: '0.8rem', padding: '0.5rem 1.25rem', height: 'fit-content' }}
          >
            {generatingBrief ? '⚡ Generating...' : '⚡ Generate Brief'}
          </button>
        </div>
      </header>

      {selectedBrief ? (
        <RenderBrief content={selectedBrief.content} />
      ) : (
        <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '6rem 2rem', color: 'var(--text-muted)' }}>
          <span className="material-symbols-outlined" style={{ fontSize: '64px', marginBottom: '1.5rem', color: 'var(--accent-pink)' }}>terminal</span>
          <h3 style={{ color: 'var(--text-primary)', marginBottom: '0.5rem', fontFamily: 'var(--font-display)' }}>No Daily Brief Telemetry</h3>
          <p style={{ marginBottom: '1.5rem', fontSize: '0.9rem', textAlign: 'center', maxWidth: '400px', color: 'var(--text-secondary)' }}>
            The morning brief log sheet has not been compiled yet. Trigger a sync check to generate the daily briefing metrics.
          </p>
          <button 
            className="btn-primary" 
            onClick={handleGenerateBrief} 
            disabled={generatingBrief}
          >
            {generatingBrief ? '⚡ Generating...' : '⚡ Generate Brief'}
          </button>
        </div>
      )}
    </div>
  );
}

export default BriefPanel;
export { parseDailyBrief, LinearMarkdownRenderer, RenderBrief };
